name: ESLint Check

on:
  push:
    branches:
      - main

jobs:
  eslint:
    name: Run ESLint on backend and frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v3에서 v4로 업데이트

      - name: Set up Node.js
        uses: actions/setup-node@v4 # v3에서 v4로 업데이트
        with:
          node-version: "20"

      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm install

      - name: Run ESLint on backend
        working-directory: ./backend
        run: npx eslint .

      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: npm install

      - name: Run ESLint on frontend
        working-directory: ./frontend
        run: npx eslint .
