name: Python Lint and Formatting

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run Black and Flake8 in fastapi_backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Run Black
        run: black --check ./fastapi_backend

      - name: Run Flake8
        run: flake8 ./fastapi_backend